[package]
name = "rust_rewritr_programming_language"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.10.1"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm14-0"] }
