[package]
name = "rust_rewritr_programming_language"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.10.1"
clap = { version = "4.4", features = ["derive"] }

[[bin]]
name = "ls-run"
path = "src/bin/ls_run.rs"